"""Update Invoice class

Revision ID: 4c7182210737
Revises: e82377002b58
Create Date: 2024-04-14 10:51:54.869221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7182210737'
down_revision: Union[str, None] = 'e82377002b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('nip', sa.String(length=12), nullable=False))
    op.add_column('invoices', sa.Column('seller_name', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('seller_address', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('seller_tax_id', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('buyer_name', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('buyer_address', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('buyer_tax_id', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('invoice_issue_date', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('product_description', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('product_measure', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('product_quantity', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('unit_price_excluding_tax', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('value_excluding_tax', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('tax_rates', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('total_net_sales_value', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('tax_amounts', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('total_amount_including_tax', sa.Float(), nullable=False))
    op.drop_column('invoices', 'price')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('invoice_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('invoices', 'total_amount_including_tax')
    op.drop_column('invoices', 'tax_amounts')
    op.drop_column('invoices', 'total_net_sales_value')
    op.drop_column('invoices', 'tax_rates')
    op.drop_column('invoices', 'value_excluding_tax')
    op.drop_column('invoices', 'unit_price_excluding_tax')
    op.drop_column('invoices', 'product_quantity')
    op.drop_column('invoices', 'product_measure')
    op.drop_column('invoices', 'product_description')
    op.drop_column('invoices', 'invoice_issue_date')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'buyer_tax_id')
    op.drop_column('invoices', 'buyer_address')
    op.drop_column('invoices', 'buyer_name')
    op.drop_column('invoices', 'seller_tax_id')
    op.drop_column('invoices', 'seller_address')
    op.drop_column('invoices', 'seller_name')
    op.drop_column('invoices', 'nip')
    # ### end Alembic commands ###
